name: SLDeathLocationBroadcaster
main: io.github.slazurin.sldeathlocationbroadcaster.SLDeathLocationBroadcaster
version: 1.2.1
author: Azurin
api-version: 1.16
softdepend: [SLVanishApi]

commands:
    death:
        description: Check last death location
        permission-message: You do not have permission to use this command.
        usage: /death
        permission: sldlb.death
    debuginfo:
        description: Check api data for SLDeathLocationBroadcaster
        permission-message: You do not have permission to use this command.
        usage: /debuginfo
        permission: sldlb.debuginfo
        
permissions:
    sldlb.*:
        default: op
        children:
            sldlb.death: true
            sldlb.death.otherplayer: true
            sldlb.deathlocation: true
            sldlb.debuginfo: true
    sldlb.death:
        description: Allows player to use the /death command
        default: true
        children:
            sldlb.death.otherplayer: true
    sldlb.death.otherplayer:
        description: Allows player to use the /death <playername> command
        default: true
    sldlb.debuginfo:
        description: Check api data for SLDeathLocationBroadcaster
        default: op